## Muhammad Usmna Tahir
### 2019-CE-34

In [49]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn import preprocessing 
from sklearn.metrics import confusion_matrix
import pandas as pd

In [25]:
data = pd.read_csv('dataset.csv')

In [26]:
# Number of times 'Yes' (freq) in the data (count)
data['Will Play'].describe()

count     400
unique      2
top       Yes
freq      201
Name: Will Play, dtype: object

In [32]:
datasetArray = np.array(data)
print(datasetArray)

[['Mild' 'Mild' 'Overcast' ... 'Open Air' 'Mild' 'Yes']
 ['High' 'Low' 'Overcast' ... 'Enclosed Environment' 'High' 'No']
 ['Low' 'Low' 'Sunny' ... 'Enclosed Environment' 'High' 'No']
 ...
 ['Low' 'Low' 'Overcast' ... 'Enclosed Environment' 'High' 'No']
 ['High' 'High' 'Overcast' ... 'Enclosed Environment' 'Low' 'Yes']
 ['High' 'Low' 'Overcast' ... 'Open Air' 'Mild' 'Yes']]


In [35]:
Features=datasetArray[:,0:-1]
print(Features)

[['Mild' 'Mild' 'Overcast' 'Cemented' 'Open Air' 'Mild']
 ['High' 'Low' 'Overcast' 'Grassy' 'Enclosed Environment' 'High']
 ['Low' 'Low' 'Sunny' 'Clay' 'Enclosed Environment' 'High']
 ...
 ['Low' 'Low' 'Overcast' 'Cemented' 'Enclosed Environment' 'High']
 ['High' 'High' 'Overcast' 'Clay' 'Enclosed Environment' 'Low']
 ['High' 'Low' 'Overcast' 'Clay' 'Open Air' 'Mild']]


In [36]:
target= datasetArray[:,-1]

In [37]:
print(target)#output

['Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No'
 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes'
 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'No'
 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes'
 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No'
 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No'
 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No'
 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes'
 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No'
 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 

In [38]:
enc =preprocessing.OrdinalEncoder() #to convert features in integer code

In [39]:
enc.fit(Features)

OrdinalEncoder()

In [40]:
features =enc.transform(Features)

In [41]:
print(features)

[[2. 2. 0. 0. 1. 2.]
 [0. 1. 0. 2. 0. 0.]
 [1. 1. 2. 1. 0. 0.]
 ...
 [1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 1. 2.]]


In [42]:
model =Perceptron()
fitted = model.fit(features,target)

In [43]:
testData = np.array(pd.read_csv('testset.csv'))
testFeatures = testData[:,:-1]
testTargets = testData[:,-1]

In [44]:
prediction= fitted.predict(enc.transform(testFeatures))

In [55]:
print(testTargets, prediction, sep='\n')

['Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes'
 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes']
['Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes']


In [54]:
# Validation
Pass = 0
Fail = 0
for i in range(len(prediction)):
    if prediction[i]==testTargets[i]:
        Pass += 1
    else:
        Fail += 1
print(f'Test Cases Passed: {Pass}\nTest Cases Failed: {Fail}\n')
print(f'Confusion matrix: \n{confusion_matrix(testTargets, prediction)}')

Test Cases Passed: 16
Test Cases Failed: 4

Confusion matrix: 
[[9 1]
 [3 7]]
